apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: app-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: marcosborba01/app-argo:1.0
        ports:
        - containerPort: 8080
